package edu.scu.dp.smartcals.ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nisha
 */
public class MonitoringStationView extends javax.swing.JPanel {

    /**
     * Creates new form MonitoringStationDashboard
     */
    public MonitoringStationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlViewVM = new javax.swing.JPanel();
        btnVM1 = new javax.swing.JButton();
        btnVM2 = new javax.swing.JButton();
        btnVM3 = new javax.swing.JButton();
        pnlAlerts = new javax.swing.JPanel();
        lblAlerts = new javax.swing.JLabel();
        pnlRevenueStat = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        pnlInventory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        pnlModifyData = new javax.swing.JPanel();
        pnlOtherStats = new javax.swing.JPanel();
        lblOtherStats = new javax.swing.JLabel();

        setAutoscrolls(true);
        setLayout(new java.awt.GridBagLayout());

        pnlViewVM.setName("ViewVM"); // NOI18N

        btnVM1.setText("VM1");
        btnVM1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVM1ActionPerformed(evt);
            }
        });

        btnVM2.setText("VM2");
        btnVM2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnVM3.setText("VM3");
        btnVM3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVM3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewVMLayout = new javax.swing.GroupLayout(pnlViewVM);
        pnlViewVM.setLayout(pnlViewVMLayout);
        pnlViewVMLayout.setHorizontalGroup(
            pnlViewVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewVMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVM1)
                .addGap(26, 26, 26)
                .addComponent(btnVM2)
                .addGap(32, 32, 32)
                .addComponent(btnVM3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewVMLayout.setVerticalGroup(
            pnlViewVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewVMLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlViewVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVM2)
                    .addComponent(btnVM1)
                    .addComponent(btnVM3))
                .addGap(29, 29, 29))
        );

        add(pnlViewVM, new java.awt.GridBagConstraints());

        lblAlerts.setText("All alerts from Observer shld be displayed here by appending text.");
        lblAlerts.setName("Alerts"); // NOI18N

        javax.swing.GroupLayout pnlAlertsLayout = new javax.swing.GroupLayout(pnlAlerts);
        pnlAlerts.setLayout(pnlAlertsLayout);
        pnlAlertsLayout.setHorizontalGroup(
            pnlAlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlertsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAlerts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAlertsLayout.setVerticalGroup(
            pnlAlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlertsLayout.createSequentialGroup()
                .addComponent(lblAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        add(pnlAlerts, gridBagConstraints);

        pnlRevenueStat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revenue Statistics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        scrollTable.setName("scrollTable"); // NOI18N

        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"test", "test", "test", "test"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rmv table and add through code", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRevenue.setName("Revenue"); // NOI18N
        scrollTable.setViewportView(tblRevenue);
        if (tblRevenue.getColumnModel().getColumnCount() > 0) {
            tblRevenue.getColumnModel().getColumn(0).setResizable(false);
            tblRevenue.getColumnModel().getColumn(1).setResizable(false);
            tblRevenue.getColumnModel().getColumn(2).setResizable(false);
            tblRevenue.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlRevenueStatLayout = new javax.swing.GroupLayout(pnlRevenueStat);
        pnlRevenueStat.setLayout(pnlRevenueStatLayout);
        pnlRevenueStatLayout.setHorizontalGroup(
            pnlRevenueStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRevenueStatLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlRevenueStatLayout.setVerticalGroup(
            pnlRevenueStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRevenueStatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        add(pnlRevenueStat, gridBagConstraints);

        pnlInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        pnlInventory.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlInventory.setPreferredSize(new java.awt.Dimension(396, 364));
        pnlInventory.setLayout(new java.awt.GridBagLayout());

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"test", "test", "test", "test"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInventory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblInventory.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setResizable(false);
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
            tblInventory.getColumnModel().getColumn(3).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlInventory.add(jScrollPane1, gridBagConstraints);
        jScrollPane1.getAccessibleContext().setAccessibleName("tblInventory");

        javax.swing.GroupLayout pnlModifyDataLayout = new javax.swing.GroupLayout(pnlModifyData);
        pnlModifyData.setLayout(pnlModifyDataLayout);
        pnlModifyDataLayout.setHorizontalGroup(
            pnlModifyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlModifyDataLayout.setVerticalGroup(
            pnlModifyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlInventory.add(pnlModifyData, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        add(pnlInventory, gridBagConstraints);

        lblOtherStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOtherStats.setText("Show other stats like Best Seller here");
        lblOtherStats.setName("OtherStats"); // NOI18N

        javax.swing.GroupLayout pnlOtherStatsLayout = new javax.swing.GroupLayout(pnlOtherStats);
        pnlOtherStats.setLayout(pnlOtherStatsLayout);
        pnlOtherStatsLayout.setHorizontalGroup(
            pnlOtherStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(pnlOtherStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherStatsLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOtherStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlOtherStatsLayout.setVerticalGroup(
            pnlOtherStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(pnlOtherStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherStatsLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOtherStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        add(pnlOtherStats, gridBagConstraints);
    }// </editor-fold>                        

    private void btnVM1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnVM3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnVM1;
    private javax.swing.JButton btnVM2;
    private javax.swing.JButton btnVM3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerts;
    private javax.swing.JLabel lblOtherStats;
    private javax.swing.JPanel pnlAlerts;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlModifyData;
    private javax.swing.JPanel pnlOtherStats;
    private javax.swing.JPanel pnlRevenueStat;
    private javax.swing.JPanel pnlViewVM;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblRevenue;
    // End of variables declaration                   
}
