package edu.scu.dp.smartcals.ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thenu
 */
public class ProductPaymentPanel extends javax.swing.JPanel {
	private VendingMachineView parentView;

    /**
     * Creates new form NewJPanel
     */
    public ProductPaymentPanel(VendingMachineView parentView) {
    	this.parentView = parentView;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblAmtPayable = new javax.swing.JLabel();
        txtAmtPayable = new javax.swing.JTextField();
        pnlCashProd = new javax.swing.JPanel();
        lblOneDollarCash = new javax.swing.JLabel();
        lblFiveDollar = new javax.swing.JLabel();
        lblTenDollar = new javax.swing.JLabel();
        txtOneDollarCash = new javax.swing.JTextField();
        txtFiveDollar = new javax.swing.JTextField();
        txtTenDollar = new javax.swing.JTextField();
        btnCash = new javax.swing.JButton();
        pnlCoinProd = new javax.swing.JPanel();
        lblQuarters = new javax.swing.JLabel();
        lblHalfDollar = new javax.swing.JLabel();
        lblOneDollar = new javax.swing.JLabel();
        txtQuarters = new javax.swing.JTextField();
        txtHalfDollar = new javax.swing.JTextField();
        txtOneDollar = new javax.swing.JTextField();
        btnCoin = new javax.swing.JButton();
        pnlSmartCardProd = new javax.swing.JPanel();
        lblSmartCard = new javax.swing.JLabel();
        txtSmartCard = new javax.swing.JTextField();
        btnSmartCard = new javax.swing.JButton();
        lblPayUnsuccess = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblAmtPayable.setText("Amount Payable:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 581, 0, 0);
        add(lblAmtPayable, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 144, 0, 0);
        add(txtAmtPayable, gridBagConstraints);

        pnlCashProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCashProd.setLayout(new java.awt.GridBagLayout());

        lblOneDollarCash.setText("one dollar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 105, 0, 0);
        pnlCashProd.add(lblOneDollarCash, gridBagConstraints);

        lblFiveDollar.setText("five dollar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(136, 97, 0, 0);
        pnlCashProd.add(lblFiveDollar, gridBagConstraints);

        lblTenDollar.setText("ten dollar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(163, 105, 0, 0);
        pnlCashProd.add(lblTenDollar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(97, 7, 0, 89);
        pnlCashProd.add(txtOneDollarCash, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 7, 0, 89);
        pnlCashProd.add(txtFiveDollar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(160, 7, 0, 89);
        pnlCashProd.add(txtTenDollar, gridBagConstraints);

        btnCash.setText("cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(106, 52, 74, 0);
        pnlCashProd.add(btnCash, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.ipady = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 86, 85, 0);
        add(pnlCashProd, gridBagConstraints);

        pnlCoinProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCoinProd.setLayout(new java.awt.GridBagLayout());

        lblQuarters.setText("quarters:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(103, 117, 0, 0);
        pnlCoinProd.add(lblQuarters, gridBagConstraints);

        lblHalfDollar.setText("half dollar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(157, 117, 0, 0);
        pnlCoinProd.add(lblHalfDollar, gridBagConstraints);

        lblOneDollar.setText("one dollar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 117, 0, 0);
        pnlCoinProd.add(lblOneDollar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 14, 0, 110);
        pnlCoinProd.add(txtQuarters, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(154, 14, 0, 110);
        pnlCoinProd.add(txtHalfDollar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(127, 3, 0, 0);
        pnlCoinProd.add(txtOneDollar, gridBagConstraints);

        btnCoin.setText("coin");
        btnCoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(97, 12, 92, 0);
        pnlCoinProd.add(btnCoin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 139, 85, 0);
        add(pnlCoinProd, gridBagConstraints);

        pnlSmartCardProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSmartCardProd.setPreferredSize(new java.awt.Dimension(609, 600));
        pnlSmartCardProd.setLayout(new java.awt.GridBagLayout());

        lblSmartCard.setText("Smart Card Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(94, 76, 0, 0);
        pnlSmartCardProd.add(lblSmartCard, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(91, 86, 0, 226);
        pnlSmartCardProd.add(txtSmartCard, gridBagConstraints);

        btnSmartCard.setText("Smart Card");
        btnSmartCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartCardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(210, 59, 347, 0);
        pnlSmartCardProd.add(btnSmartCard, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.ipady = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 81, 85, 26);
        add(pnlSmartCardProd, gridBagConstraints);

        lblPayUnsuccess.setText("Not Enough Cash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 239, 0, 0);
        add(lblPayUnsuccess, gridBagConstraints);
    }// </editor-fold>                        

    private void btnCoinActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnSmartCardActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnCoin;
    private javax.swing.JButton btnSmartCard;
    private javax.swing.JLabel lblAmtPayable;
    private javax.swing.JLabel lblFiveDollar;
    private javax.swing.JLabel lblHalfDollar;
    private javax.swing.JLabel lblOneDollar;
    private javax.swing.JLabel lblOneDollarCash;
    private javax.swing.JLabel lblPayUnsuccess;
    private javax.swing.JLabel lblQuarters;
    private javax.swing.JLabel lblSmartCard;
    private javax.swing.JLabel lblTenDollar;
    private javax.swing.JPanel pnlCashProd;
    private javax.swing.JPanel pnlCoinProd;
    private javax.swing.JPanel pnlSmartCardProd;
    private javax.swing.JTextField txtAmtPayable;
    private javax.swing.JTextField txtFiveDollar;
    private javax.swing.JTextField txtHalfDollar;
    private javax.swing.JTextField txtOneDollar;
    private javax.swing.JTextField txtOneDollarCash;
    private javax.swing.JTextField txtQuarters;
    private javax.swing.JTextField txtSmartCard;
    private javax.swing.JTextField txtTenDollar;
    // End of variables declaration                   
}
