package edu.scu.dp.smartcals.ui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nisha
 */
public class VMDetails_View extends javax.swing.JPanel {

    /**
     * Creates new form panel3
     */
    public VMDetails_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSelectOrder = new javax.swing.JPanel();
        btnAddItem = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JPanel();
        lblDisplay = new javax.swing.JLabel();
        pnlSmartCard = new javax.swing.JPanel();
        btnLoadCard = new javax.swing.JButton();
        btnBuySmartCard = new javax.swing.JButton();
        btnNutriInfo = new javax.swing.JButton();
        pnlDispenser = new javax.swing.JPanel();
        lblCoinDispense = new javax.swing.JLabel();
        lblCashDispense = new javax.swing.JLabel();
        lblCardDispense = new javax.swing.JLabel();
        lblItemDispense = new javax.swing.JLabel();
        pnlPayment = new javax.swing.JPanel();
        btnPayCoin = new javax.swing.JButton();
        btnPayCash = new javax.swing.JButton();
        btnPayCard = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pnlSelectOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlSelectOrder.setName("pnlSelectOrder"); // NOI18N

        btnAddItem.setText("Add Item");
        btnAddItem.setName("btnAddItem"); // NOI18N

        btnCheckout.setText("Checkout");
        btnCheckout.setName("btnCheckout"); // NOI18N

        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.setName("btnCancelOrder"); // NOI18N

        javax.swing.GroupLayout pnlSelectOrderLayout = new javax.swing.GroupLayout(pnlSelectOrder);
        pnlSelectOrder.setLayout(pnlSelectOrderLayout);
        pnlSelectOrderLayout.setHorizontalGroup(
            pnlSelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );
        pnlSelectOrderLayout.setVerticalGroup(
            pnlSelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectOrderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.7;
        add(pnlSelectOrder, gridBagConstraints);

        pnlDisplay.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 204)));
        pnlDisplay.setName("pnlDisplay"); // NOI18N

        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplay.setText("SmartCals Vending Machine");
        lblDisplay.setName("lblDisplay"); // NOI18N

        javax.swing.GroupLayout pnlDisplayLayout = new javax.swing.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayLayout.createSequentialGroup()
                .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.9;
        add(pnlDisplay, gridBagConstraints);

        pnlSmartCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlSmartCard.setName("pnlSmartCard"); // NOI18N

        btnLoadCard.setText("Load Smart Card");
        btnLoadCard.setName("btnLoadCard"); // NOI18N

        btnBuySmartCard.setText("Buy Smart Card");
        btnBuySmartCard.setName("btnBuySmartCard"); // NOI18N

        btnNutriInfo.setText("Nutritional Information");
        btnNutriInfo.setName("btnNutriInfo"); // NOI18N
        btnNutriInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNutriInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSmartCardLayout = new javax.swing.GroupLayout(pnlSmartCard);
        pnlSmartCard.setLayout(pnlSmartCardLayout);
        pnlSmartCardLayout.setHorizontalGroup(
            pnlSmartCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuySmartCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSmartCardLayout.createSequentialGroup()
                .addGroup(pnlSmartCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNutriInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnLoadCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        pnlSmartCardLayout.setVerticalGroup(
            pnlSmartCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSmartCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNutriInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadCard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuySmartCard, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.6;
        add(pnlSmartCard, gridBagConstraints);

        pnlDispenser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlDispenser.setName("pnlDispenser"); // NOI18N

        lblCoinDispense.setText("Dispense Coin");
        lblCoinDispense.setName("lblCoinDispense"); // NOI18N

        lblCashDispense.setText("Dispense Cash");
        lblCashDispense.setName("lblCashDispense"); // NOI18N

        lblCardDispense.setBackground(new java.awt.Color(0, 0, 0));
        lblCardDispense.setText("Card");
        lblCardDispense.setName("lblCardDispense"); // NOI18N

        lblItemDispense.setText("Item Dispenser");

        javax.swing.GroupLayout pnlDispenserLayout = new javax.swing.GroupLayout(pnlDispenser);
        pnlDispenser.setLayout(pnlDispenserLayout);
        pnlDispenserLayout.setHorizontalGroup(
            pnlDispenserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDispenserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDispenserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDispenserLayout.createSequentialGroup()
                        .addComponent(lblItemDispense, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(pnlDispenserLayout.createSequentialGroup()
                        .addGroup(pnlDispenserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCashDispense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCoinDispense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCardDispense, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        pnlDispenserLayout.setVerticalGroup(
            pnlDispenserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDispenserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDispenserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDispenserLayout.createSequentialGroup()
                        .addComponent(lblCoinDispense, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCashDispense, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCardDispense, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemDispense, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        add(pnlDispenser, gridBagConstraints);

        pnlPayment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Via", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlPayment.setName("pnlPayment"); // NOI18N

        btnPayCoin.setText("Coins");
        btnPayCoin.setName("btnPayCoin"); // NOI18N

        btnPayCash.setText("Cash");
        btnPayCash.setName("btnPayCash"); // NOI18N

        btnPayCard.setText("SmartCard");
        btnPayCard.setName("btnPayCard"); // NOI18N

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentLayout.createSequentialGroup()
                        .addComponent(btnPayCoin, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPayCash, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(pnlPaymentLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnPayCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPayCoin)
                    .addComponent(btnPayCash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPayCard)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        add(pnlPayment, gridBagConstraints);
    }// </editor-fold>                        

    private void btnNutriInfoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBuySmartCard;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnLoadCard;
    private javax.swing.JButton btnNutriInfo;
    private javax.swing.JButton btnPayCard;
    private javax.swing.JButton btnPayCash;
    private javax.swing.JButton btnPayCoin;
    private javax.swing.JLabel lblCardDispense;
    private javax.swing.JLabel lblCashDispense;
    private javax.swing.JLabel lblCoinDispense;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblItemDispense;
    private javax.swing.JPanel pnlDispenser;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlSelectOrder;
    private javax.swing.JPanel pnlSmartCard;
    // End of variables declaration                   
}
