package edu.scu.dp.smartcals.ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nisha
 */
public class VMSelection_View extends javax.swing.JPanel {

    /**
     * Creates new form SelectVM
     */
    public VMSelection_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnSchool1 = new javax.swing.JButton();
        btnSchool2 = new javax.swing.JButton();
        btnHospital1 = new javax.swing.JButton();
        btnHospital2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        btnSchool1.setText("SCU School");
        btnSchool1.setName("btnSchool1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 60, 80);
        add(btnSchool1, gridBagConstraints);

        btnSchool2.setText("SJSU School");
        btnSchool2.setName("btnSchool2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 60, 80);
        add(btnSchool2, gridBagConstraints);

        btnHospital1.setText("Good Samaritan Hospital");
        btnHospital1.setName("btnHospital1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 60, 80);
        add(btnHospital1, gridBagConstraints);

        btnHospital2.setText("O'Connor Hospital");
        btnHospital2.setName("btnHospital2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 60, 80);
        add(btnHospital2, gridBagConstraints);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnHospital1;
    private javax.swing.JButton btnHospital2;
    private javax.swing.JButton btnSchool1;
    private javax.swing.JButton btnSchool2;
    // End of variables declaration                   
}
