/**
 * 
 */
package edu.scu.dp.smartcals.ui;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import edu.scu.dp.smartcals.vm.Beverage;
import edu.scu.dp.smartcals.vm.VMController;
import edu.scu.dp.smartcals.vm.VendingMachine;

/**
 * @author Aparna Ganesh
 *
 */
public class VMViewProductsFrame extends JFrame {

	private VendingMachine vendingMachine;

	private VMController vmController;

	// Variables declaration - do not modify
	private javax.swing.JButton btnCandy;
	private javax.swing.JButton btnSnack;
	private javax.swing.JButton btnBev;
	private javax.swing.JPanel pnlCategory;

	// End of variables declaration

	/**
	 * Creates new form NewJPanel
	 */
	public VMViewProductsFrame(VMController vmController, long vmId) {

		this.vmController = vmController;
		loadVM(vmId);
		initComponents();
	}

	/**
	 * Gets VendingMachine Products for a given Id from Controller To display in
	 * UI.
	 * 
	 * @param vmId
	 */

	private void loadVM(long vmId) {
		vendingMachine = vmController.getVendingMachine(vmId);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pnlCategory = new javax.swing.JPanel();
		btnBev = new javax.swing.JButton();
		btnSnack = new javax.swing.JButton();
		btnCandy = new javax.swing.JButton();
		
		VMProductCategoryActionListener prodBtnActionListener = new VMProductCategoryActionListener();

		//setLayout(new java.awt.GridBagLayout());
		setLayout(new java.awt.FlowLayout());

		//pnlCategory.setLayout(new java.awt.GridBagLayout());
		pnlCategory.setLayout(new java.awt.FlowLayout());

		btnBev.setText("Beverage");
		btnBev.setActionCommand("Beverage");
		btnBev.addActionListener(prodBtnActionListener);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 77;
		gridBagConstraints.ipady = 40;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(76, 235, 86, 0);
		//pnlCategory.add(btnBev, gridBagConstraints);
		pnlCategory.add(btnBev);

		btnSnack.setText("Snack");
		btnSnack.setActionCommand("Snack");
		btnSnack.addActionListener(prodBtnActionListener);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 119;
		gridBagConstraints.ipady = 40;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(76, 199, 86, 0);
		//pnlCategory.add(btnSnack, gridBagConstraints);
		pnlCategory.add(btnSnack);

		btnCandy.setText("Candy");
		btnCandy.setActionCommand("Candy");
		btnCandy.addActionListener(prodBtnActionListener);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 115;
		gridBagConstraints.ipady = 40;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(76, 203, 86, 353);
		//pnlCategory.add(btnCandy, gridBagConstraints);
		pnlCategory.add(btnCandy);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 258;
		gridBagConstraints.ipady = 58;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
		gridBagConstraints.weightx = 0.5;
		
		//add(pnlCategory, gridBagConstraints);
		add(pnlCategory);

		setContentPane(pnlCategory);
		pack();
		setVisible(true);
		
	}// </editor-fold>

	/**
	 * On button click of Beverage,Snack,Candy products shuold be displayed
	 * 
	 * @author Aparna Ganesh
	 *
	 */
	class VMProductCategoryActionListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

			String actionCommand = e.getActionCommand();
			if (actionCommand.equals("Beverage")) {
				List<Beverage> beverageList = vendingMachine.getBeverages();

				for (Beverage beverage : beverageList) {
					JPanel prodInfoPanel = new ProductInfoPanel(beverage.getProductID()+ "",beverage.getProductName(),beverage.getProductPrice()+"");
					pnlCategory.add(prodInfoPanel);
					System.out.println(beverage.getProductID());
				}
				pnlCategory.revalidate();
			}
		}

	}

	class ProductInfoPanel extends JPanel {
		
		private JLabel productIdLbl;
		private JLabel productNameLbl;
		private JLabel productPriceLbl;
		
		public ProductInfoPanel(String id,String name,String price) {
			productIdLbl = new JLabel(id);
			productNameLbl = new JLabel(name);
			productPriceLbl = new JLabel(price);
			setLayout(new GridLayout(3,1));
			add(productIdLbl);
			add(productNameLbl);
			add(productPriceLbl);
		}
		
	}
	public static void main(String[] args) {

		VMViewProductsFrame frame = new VMViewProductsFrame(new VMController(),
				1000);
		frame.initComponents();
		frame.pack();

	}
}